replicaCount: 1

image:
  repository: <your-ecr-repo-url>  # Will be set by GitHub Actions
  tag: latest                      # Will be overridden by Actions
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 5000

