replicaCount: 2

image:
  repository: 405325454731.dkr.ecr.us-east-1.amazonaws.com/flask-app2.0
                      # e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/flask-eks-app
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}

