name: Build & Push Flask App

on:
  push:
    branches:
      - main

env:
  ECR_REPO: ${{ secrets.ECR_REPO_URI }}
  REGION: ${{ secrets.AWS_REGION }}

jobs:
  build_and_push:
    name: Build and Push Docker Image to ECR
    runs-on: [eks-runer]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract short SHA
      id: vars
      run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPO:$TAG .
        docker tag $ECR_REPO:$TAG $ECR_REPO:latest

    - name: Push to Amazon ECR
      run: |
        docker push $ECR_REPO:$TAG
        docker push $ECR_REPO:latest
    
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ env.REGION }}

    - name: Deploy with Helm to EKS
      run: |
        helm upgrade --install flask-app ./helm/flask-app \
          --set image.repository=${{ secrets.ECR_REPO_URI }} \
          --set image.tag=$TAG \
          --set service.type=LoadBalancer

